WebApplication_Blog/Controllers/Admin/AdmnCategoryController.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.Controllers.Admin
{
    [Authorize]
    public class AdmnCategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        private readonly IBlogService _blogService;

        public AdmnCategoryController(ICategoryService categoryService, IMapper mapper, IBlogService blogService)
        {
            _categoryService = categoryService;
            _mapper = mapper;
            _blogService = blogService;
        }

        public IActionResult Index()
        {
            var categories = _categoryService.GetList();
            var mappedList = _mapper.Map<List<CategoryViewModel>>(categories);
            foreach (var item in mappedList)
            {
                item.BlogCount = _blogService.GetBlogCountByCategory(item.CategoryId);
            }
            return View(mappedList);
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryViewModel model)
        {
            model.CategoryStatus = true;
            _categoryService.Add(_mapper.Map<Category>(model));
            return RedirectToAction("Index");
        }
        public IActionResult CategoryStatus(int id)
        {
            var category = _categoryService.GetById(id);
            if (category.CategoryStatus == true)
            {
                category.CategoryStatus = false;
            }
            else
            {
                category.CategoryStatus = true;
            }
            _categoryService.Update(category);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var category = _categoryService.GetById(id);
            return View(_mapper.Map<CategoryViewModel>(category));
        }
        [HttpPost]
        public IActionResult Edit(CategoryViewModel model)
        {
            _categoryService.Update(_mapper.Map<Category>(model));
            return RedirectToAction("Index");
        }
    }
}

WebApplication_Blog/Controllers/Admin/AdmnCommentController.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using EntityLayer.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.Controllers.Admin
{
    [Authorize]
    public class AdmnCommentController : Controller
    {
        private readonly ICommentDal _commentDal;
        private readonly IMapper _mapper;
        private readonly ICommentReplyService _replyService;

        public AdmnCommentController(ICommentDal commentDal, IMapper mapper, ICommentReplyService replyService)
        {
            _commentDal = commentDal;
            _mapper = mapper;
            _replyService = replyService;
        }

        public IActionResult Index()
        {
            var comments = _commentDal.GetListAll();
            return View(_mapper.Map<List<CommentViewModel>>(comments));
        }
        public IActionResult CommentStatus(int id)
        {
            var comment = _commentDal.GetById(id);
            if (comment.CommentStatus == true)
            {
                comment.CommentStatus = false;
            }
            else
            {
                comment.CommentStatus = true;
            }
            _commentDal.Update(comment);
            return RedirectToAction("Index");
        }
        public IActionResult ReplyCommentStatus(int id)
        {
            var replycomment = _replyService.GetById(id);
            if (replycomment.CommentStatus == true)
            {
                replycomment.CommentStatus = false;
            }
            else
            {
                replycomment.CommentStatus = true;
            }
            _replyService.Update(replycomment);
            return RedirectToAction("Edit", new {id= replycomment.CommentId});
        }
        public IActionResult Edit(int id)
        {
            var comment = _commentDal.GetById(id);
            return View(_mapper.Map<CommentViewModel>(comment));
        }
    }
}

WebApplication_Blog/Controllers/Admin/AdmnController.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using DataAccessLayer.Identity;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.Controllers.Admin
{
    [Authorize]
    public class AdmnController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IMapper _mapper;
        private readonly ICommentService _commentService;
        private readonly ICategoryService _categoryService;


        public AdmnController(IBlogService blogService, IMapper mapper, ICommentService commentService, ICategoryService categoryService)
        {
            _blogService = blogService;
            _mapper = mapper;
            _commentService = commentService;
            _categoryService = categoryService;

        }

        public IActionResult Index()
        {
            var values = _blogService.GetAllBlogsWithCategory();
            ViewBag.Blogs = _mapper.Map<List<BlogViewModel>>(values).Count();
            values.Reverse();
            ViewBag.Comments = _mapper.Map<List<CommentViewModel>>(_commentService.GetList()).Count();
            return View(_mapper.Map<List<BlogViewModel>>(values).Take(3).ToList());
        }
        public IActionResult AllBlogs()
        {
            var blogs = _blogService.GetBlogsWithCategory();
            blogs.Reverse();
            return View(_mapper.Map<List<BlogViewModel>>(blogs));
        }
        public IActionResult BlogStatus(int id)
        {
            var blog = _blogService.GetById(id);
            if (blog.BlogStatus == true)
            {
                blog.BlogStatus = false;
            }
            else
            {
                blog.BlogStatus = true;
            }
            _blogService.Update(blog);
            return RedirectToAction("AllBlogs");
        }
        public IActionResult Edit(int id)
        {
            var blog = _blogService.GetById(id);
            ViewBag.Categories = new SelectList(_categoryService.GetList(), "CategoryId", "CategoryName");
            return View(_mapper.Map<BlogViewModel>(blog));
        }
        public IActionResult CreateBlog()
        {
            ViewBag.Categories = new SelectList(_categoryService.GetList(), "CategoryId", "CategoryName");
            return View();
        }
        [HttpPost]
        public IActionResult CreateBlog(BlogViewModel blog, IFormFile formFile1, IFormFile formFile2)
        {
            //Thumbnail Image
            var path1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", formFile1.FileName);
            //Content Image
            var path2 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", formFile2.FileName);
            var stream1 = new FileStream(path1, FileMode.Create);
            var stream2 = new FileStream(path2, FileMode.Create);
            formFile1.CopyTo(stream1);
            formFile2.CopyTo(stream2);
            blog.BlogThumbnailImage = "/images/" + formFile1.FileName;
            blog.BlogImage = "/images/" + formFile2.FileName;
            blog.BlogCreateDate = DateTime.Now;
            _blogService.Add(_mapper.Map<Blog>(blog));

            ViewBag.Categories = new SelectList(_categoryService.GetList(), "CategoryId", "CategoryName");
            return View();
        }

        
    }
}

WebApplication_Blog/Controllers/BlogController.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using BuisnessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Abstract;
using EntityLayer.Concrete;
using EntityLayer.Repositories;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IMapper _mapper;

        public BlogController(IBlogService blogService, IMapper mapper)
        {
            _blogService = blogService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var values = _blogService.GetAllBlogsWithCategory();
            values.Reverse();
            return View(_mapper.Map<List<BlogViewModel>>(values));
        }
        public IActionResult Blogs(int? id, string search)
        {
            var values = _blogService.GetAllBlogsWithCategory();
            values.Reverse();
            if (id != null)
            {
                values = _blogService.GetAllBlogsByCategoryId(id);
                values.Reverse();
            }
            if (search != null)
            {
                values = _blogService.GetListWithSearch(search);
            }
            
            
            return View(_mapper.Map<List<BlogViewModel>>(values));
        }
        
        public IActionResult BlogDetails(int id)
        {
            var values = _blogService.GetBlogsWithCategory(id);
            return View(_mapper.Map<BlogViewModel>(values));
        }
    }
}

WebApplication_Blog/Views/Shared/AddCommentPartial.cshtml
@model CommentViewModel

<div class="col-lg-12">
    <div class="sidebar-item submit-comment">
        <div class="sidebar-heading">
            <h2>Yorumunuz</h2>
        </div>
        <div class="content">
            <form id="comment">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <input asp-for="BlogId" type="hidden" value="@Model.BlogId">
                        <fieldset>
                            <input asp-for="CommentUserName" type="text" id="name" placeholder="Adınız" required="">
                        </fieldset>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <fieldset>
                            <input asp-for="CommentEmail" type="text" id="email" placeholder="E-posta Adresiniz" required="">
                        </fieldset>
                    </div>
                    <div class="col-lg-12">
                        <fieldset>
                            <textarea asp-for="CommentContent" rows="6" id="message" placeholder="Yorumunuzu buraya yazın" required=""></textarea>
                        </fieldset>
                    </div>
                    <div class="col-lg-12">
                        <fieldset>
                            <button type="button" id="form-submit" onclick="AddComment()" class="main-button">Gönder</button>
                        </fieldset>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication_Blog/Views/Shared/AddReplyCommentPartial.cshtml
@model ReplyCommentViewModel

<div class="col-lg-12">
    <div class="sidebar-item submit-comment">
        <div class="sidebar-heading">
            <h2>Your comment</h2>
        </div>
        <div class="content">
            <form id="replycomment">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <input asp-for="CommentId" type="hidden" value="@Model.CommentId">
                        <input asp-for="BlogId" type="hidden" value="@Model.BlogId">
                        <fieldset>
                            <input asp-for="CommentUserName" type="text" id="name" placeholder="Your name" required="">
                        </fieldset>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <fieldset>
                            <input asp-for="CommentEmail" type="text" id="email" placeholder="Your email" required="">
                        </fieldset>
                    </div>
                    <div class="col-lg-12">
                        <fieldset>
                            <textarea asp-for="CommentContent" rows="6" id="message" placeholder="Type your comment" required=""></textarea>
                        </fieldset>
                    </div>
                    <div class="col-lg-12">
                        <fieldset>
                            <button type="button" id="form-submit" onclick="AddReplyComment()" class="main-button">Gönder</button>
                        </fieldset>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication_Blog/Views/Shared/AdminFooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates </a> from Bootstrapdash.com</span>
    </div>
</footer>

WebApplication_Blog/Views/Shared/AdminNavbarPartial.cshtml
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html"><img src="~/admin/assets/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/admin/assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </div>
                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                </div>
            </form>
        </div>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="~/admin/assets/images/faces/face1.jpg" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">David Greymaax</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached mr-2 text-success"></i> Activity Log
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-logout mr-2 text-primary"></i> Signout
                    </a>
                </div>
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
                <a class="nav-link">
                    <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-email-outline"></i>
                    <span class="count-symbol bg-warning"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <h6 class="p-3 mb-0">Messages</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/admin/assets/images/faces/face4.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
                            <p class="text-gray mb-0"> 1 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/admin/assets/images/faces/face2.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
                            <p class="text-gray mb-0"> 15 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/admin/assets/images/faces/face3.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
                            <p class="text-gray mb-0"> 18 Minutes ago </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">4 new messages</h6>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count-symbol bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <h6 class="p-3 mb-0">Notifications</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-success">
                                <i class="mdi mdi-calendar"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
                            <p class="text-gray ellipsis mb-0"> Just a reminder that you have an event today </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-warning">
                                <i class="mdi mdi-settings"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
                            <p class="text-gray ellipsis mb-0"> Update dashboard </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-link-variant"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
                            <p class="text-gray ellipsis mb-0"> New admin wow! </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">See all notifications</h6>
                </div>
            </li>
            <li class="nav-item nav-logout d-none d-lg-block">
                <a class="nav-link" asp-action="Logout" asp-controller="Account">
                    <i class="mdi mdi-power"></i>
                </a>
            </li>
            <li class="nav-item nav-settings d-none d-lg-block">
                <a class="nav-link" href="#">
                    <i class="mdi mdi-format-line-spacing"></i>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

WebApplication_Blog/Views/Shared/AdminSidebarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/admin/assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status offline"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">David Grey. H</span>
                    <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Admn" asp-action="Index">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Admn" asp-action="AllBlogs">
                <span class="menu-title">Bütün Bloglar</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="AdmnCategory" asp-action="Index">
                <span class="menu-title">Kategoriler</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="AdmnComment">
                <span class="menu-title">Yorumlar</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="pages/tables/basic-table.html">
                <span class="menu-title">Siteye Dön</span>
                <i class="mdi mdi-table-large menu-icon"></i>
            </a>
        </li>
        <li class="nav-item sidebar-actions">
            <span class="nav-link">

                <a class="btn btn-block btn-lg btn-gradient-primary" asp-action="CreateBlog" asp-controller="Admn">+ Yeni Blog</a>
                <a class="btn btn-block btn-lg btn-gradient-primary" asp-action="CreateCategory" asp-controller="AdmnCategory">+ Yeni Kategori</a>

            </span>
        </li>
    </ul>
</nav>

WebApplication_Blog/Views/Shared/FooterPartial.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <ul class="social-icons">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Behance</a></li>
                <li><a href="#">Linkedin</a></li>
                <li><a href="#">Dribbble</a></li>
            </ul>
        </div>
        <div class="col-lg-12">
            <div class="copyright-text">
                <p>
                    Copyright &copy; @DateTime.Now.Year 

                    | Design: <strong>EMRE BOYABAT</strong>
                </p>
            </div>
        </div>
    </div>
</div>

WebApplication_Blog/Views/Shared/HeaderPartial.cshtml
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" asp-controller="Blog" asp-action="Index"><h2>EMRE BOYABAT<em>.</em></h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link @(ViewContext.RouteData.Values["action"].ToString() == "Index" && ViewContext.RouteData.Values["controller"].ToString() == "Blog" ? "active" : "")" asp-action="Index" asp-controller="Blog">
                        Ana Sayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(ViewContext.RouteData.Values["action"].ToString() == "Blogs" ? "active" : "")" asp-action="Blogs" asp-controller="Blog">Bloglar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(ViewContext.RouteData.Values["action"].ToString() == "Index" && ViewContext.RouteData.Values["controller"].ToString() == "About" ? "active" : "")" asp-action="Index" asp-controller="About">Hakkımda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(ViewContext.RouteData.Values["action"].ToString() == "AddComment" ? "active" : "")" href="contact.html">İletişim</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

WebApplication_Blog/Views/Shared/_AboutLayout.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand Blog - About Page</title>

    <!-- Bootstrap core CSS -->
    <link href="~/blogtemplate/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/blogtemplate/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/blogtemplate/assets/css/templatemo-stand-blog.css">
    <link rel="stylesheet" href="~/blogtemplate/assets/css/owl.css">
    <!--


    -->
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- Header -->
    <header class="">
        <partial name="HeaderPartial" />
    </header>

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        
    </div>
    
    <!-- Banner Ends Here -->
    @RenderBody()
    <!-- Footer Start Here -->
    <footer>
        <partial name="FooterPartial" />
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/blogtemplate/vendor/jquery/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/blogtemplate/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <!-- Additional Scripts -->
    <script src="~/blogtemplate/assets/js/custom.js"></script>
    <script src="~/blogtemplate/assets/js/owl.js"></script>
    <script src="~/blogtemplate/assets/js/slick.js"></script>
    <script src="~/blogtemplate/assets/js/isotope.js"></script>
    <script src="~/blogtemplate/assets/js/accordions.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) {                   //declaring the array outside of the
            if (!cleared[t.id]) {                      // function makes it static and global
                cleared[t.id] = 1;  // you could use true and false, but that's more typing
                t.value = '';         // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>

</body>
</html>