WebApplication_Blog/ViewModels/BlogViewModel.cs
using EntityLayer.Concrete;

namespace WebApplication_Blog.ViewModels
{
    public class BlogViewModel
    {
        public int BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string BlogContent { get; set; }
        public string BlogThumbnailImage { get; set; }
        public string BlogImage { get; set; }
        public DateTime BlogCreateDate { get; set; }
        public bool BlogStatus { get; set; }
        public int CommentCount { get; set; }
        public string BlogTags { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

WebApplication_Blog/Controllers/BlogController.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using BuisnessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Abstract;
using EntityLayer.Concrete;
using EntityLayer.Repositories;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IMapper _mapper;

        public BlogController(IBlogService blogService, IMapper mapper)
        {
            _blogService = blogService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var values = _blogService.GetAllBlogsWithCategory();
            values.Reverse();
            return View(_mapper.Map<List<BlogViewModel>>(values));
        }
        public IActionResult Blogs(int? id, string search)
        {
            var values = _blogService.GetAllBlogsWithCategory();
            values.Reverse();
            if (id != null)
            {
                values = _blogService.GetAllBlogsByCategoryId(id);
                values.Reverse();
            }
            if (search != null)
            {
                values = _blogService.GetListWithSearch(search);
            }
            
            
            return View(_mapper.Map<List<BlogViewModel>>(values));
        }
        
        public IActionResult BlogDetails(int id)
        {
            var values = _blogService.GetBlogsWithCategory(id);
            return View(_mapper.Map<BlogViewModel>(values));
        }
    }
}

WebApplication_Blog/ViewComponents/Comment/CommentViewComponent.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.ViewComponents.Comment
{
    public class CommentViewComponent : ViewComponent
    {
        private readonly ICommentService _commentService;
        private readonly IMapper _mapper;

        public CommentViewComponent(ICommentService commentService, IMapper mapper)
        {
            _commentService = commentService;
            _mapper = mapper;
        }
        public IViewComponentResult Invoke(int id) 
        {
            var values = _commentService.GetList(id).Where(x => x.CommentStatus == true);
            values.Reverse();
            return View(_mapper.Map<List<CommentViewModel>>(values)); 
        }
    }
}

WebApplication_Blog/Views/Blog/BlogDetails.cshtml
@model BlogViewModel

@{
    ViewData["Title"] = "BlogDetails";
    Layout = "~/Views/Shared/_AllBlogsLayout.cshtml";
}
@*@{

    var tags = Model.BlogTags.Split(',').Select(tag => tag.Trim()).ToList();
}*@
<div class="col-lg-8">
    <div class="all-blog-posts">
        <div class="row">
            <div class="col-lg-12">
                <div class="blog-post">
                    <div class="blog-thumb">
                        <img src="@Model.BlogThumbnailImage" alt="">
                    </div>
                    <div class="down-content">
                        <span>@Model.Category.CategoryName</span>
                        <a href="post-details.html"><h4>@Model.BlogTitle</h4></a>
                        <ul class="post-info">
                            <li>@Model.BlogCreateDate.ToString("dd-MMM-yyyy")</li>
                            <li>10 Yorum</li>
                        </ul>
                        <div>
                                @Html.Raw(Model.BlogContent)
                        </div>
                        <div class="post-options">
                            <div class="row">
                                <div class="col-6">
                                    <ul class="post-tags">
                                        <li><i class="fa fa-tags"></i></li>
                                        @foreach (var item in Model.BlogTags.Split(",").ToList())
                                        {
                                            <li><a href="#">@item</a></li>
                                        }

                                    </ul>
                                </div>
                                <div class="col-6">
                                    <ul class="post-share">
                                        <li><i class="fa fa-share-alt"></i></li>
                                        <li><a href="#">Facebook</a>,</li>
                                        <li><a href="#"> Twitter</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Comment Adding Start Here -->
            @await Html.PartialAsync("AddCommentPartial",new CommentViewModel{BlogId=Model.BlogId})
            <!-- Comment Adding End Here -->
            <!-- Comments Start Here -->

            <div class="col-lg-12 mt-5">
                <vc:comment id=@Model.BlogId></vc:comment>
            </div>
            <!-- Comments End Here -->

        </div>
    </div>
</div>

WebApplication_Blog/Views/Blog/Blogs.cshtml
@model List<BlogViewModel>
@{
    ViewData["Title"] = "Blogs";
    Layout = "~/Views/Shared/_AllBlogsLayout.cshtml";
}
@{
    var pageSize = 6; // Her sayfada gösterilecek blog sayısı
    var pageCount = (int)Math.Ceiling((double)Model.Count / pageSize);

    var httpContext = ViewContext.HttpContext;
    var pageNumber = 1; // Varsayılan sayfa numarası
    if (httpContext.Request.Query.ContainsKey("page") && int.TryParse(httpContext.Request.Query["page"], out int parsedPage)) //
    {
        pageNumber = parsedPage;
    }

    var blogsToShow = Model.Skip((pageNumber - 1) * pageSize).Take(pageSize);
}


<div class="col-lg-8">
    <div class="all-blog-posts">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-6">
                    <div class="blog-post">
                        <div class="blog-thumb">
                            <a asp-action="BlogDetails" asp-controller="Blog" asp-route-id="@item.BlogId"><img src="@item.BlogThumbnailImage" alt=""></a>
                        </div>
                        <div class="down-content">
                            <span>@item.Category.CategoryName</span>
                            <a asp-action="BlogDetails" asp-controller="Blog"><h4>@item.BlogTitle</h4></a>
                            <ul class="post-info">
                                <li>@item.BlogCreateDate.ToString("dd-MMM-yyyy")</li>
                                <li><vc:Comment-Count id=@item.BlogId></vc:Comment-Count></li> Adet Yorum
                            </ul>
                            <p>
                               
                                    @Html.Raw(item.BlogContent.Substring(0,item.BlogContent.Substring(0,130).LastIndexOf(" ")))
                                <p>...</p>
                              
                            </p>
                            <div class="post-options">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <ul class="post-tags">
                                            <li><i class="fa fa-tags"></i></li>
                                            <li>@item.BlogTags</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="col-lg-12">
                <ul class="page-numbers">
                    @for (int i = 1; i <= pageCount; i++)
                    {
                        <li @(i == pageNumber ? "class=active" : "")><a href="?page=@i">@i</a></li>
                        //Seçilen satırı işaretleme
                    }
                </ul>
            </div>

        </div>
    </div>
</div>

WebApplication_Blog/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_BlogLayout.cshtml";
}
@model List<BlogViewModel>


<div class="col-lg-8">
    <div class="all-blog-posts">
        @foreach (var item in Model)
        {
            <div class="row">
                <div class="col-lg-12">
                    <div class="blog-post">
                        <div class="blog-thumb">
                            <a asp-route-id="@item.BlogId" asp-action="BlogDetails" asp-controller="Blog"><img src="@item.BlogThumbnailImage" alt=""></a>
                        </div>
                        <div class="down-content">
                            <span>@item.Category.CategoryName</span>
                            <a asp-route-id="@item.BlogId" asp-action="BlogDetails" asp-controller="Blog"><h4>@item.BlogTitle</h4></a>
                            <ul class="post-info">
                                <li>@item.BlogCreateDate.ToString("dd-MMM-yyyy")</li>
                                <li><vc:Comment-Count id=@item.BlogId></vc:Comment-Count></li> Adet Yorum
                            </ul>
                            <br>
                            <br>
                            <div>

                                @Html.Raw(item.BlogContent.Substring(0,item.BlogContent.Substring(0,130).LastIndexOf(" ")))
                                    <span>...</span>

                            </div>
                            <div class="post-options">
                                <div class="row">
                                    <div class="col-6">
                                        <ul class="post-tags">
                                            <li><i class="fa fa-tags"></i></li>
                                            @foreach (var tags in item.BlogTags.Split(",").ToList())
                                            {
                                                <li><a href="#">@tags</a>,</li>
                                            }
                                        </ul>
                                    </div>
                                    <div class="col-6">
                                        <ul class="post-share">
                                            <li><i class="fa fa-share-alt"></i></li>
                                            <li><a href="#">Facebook</a>,</li>
                                            <li><a href="#"> Twitter</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center">
                    <a asp-action="Blogs" asp-controller="Blog" class="btn" style="background-color:#f48840; color:white;">Bütün Bloglar</a>
                </div>
            </div>
        </div>
    </div>
</div>