WebApplication_Blog/ViewModels/CommentViewModel.cs
namespace WebApplication_Blog.ViewModels
{
    public class CommentViewModel
    {
        public int CommentId { get; set; }
        public string CommentUserName { get; set; }
        public string CommentEmail { get; set; }
        public string CommentContent { get; set; }
        public DateTime CommentDate { get; set; }
        public bool CommentStatus { get; set; }
        public int BlogId { get; set; }
    }
}

WebApplication_Blog/Controllers/CommentController.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly IMapper _mapper;
        private readonly ICommentReplyService _commentReplyService;

        public CommentController(ICommentService commentService, IMapper mapper, ICommentReplyService commentReplyService)
        {
            _commentService = commentService;
            _mapper = mapper;
            _commentReplyService = commentReplyService;
        }

        [HttpPost]
        public IActionResult AddComment(CommentViewModel comment)
        {
            comment.CommentDate = DateTime.Now;
            comment.CommentStatus = false;
            _commentService.Add(_mapper.Map<Comment>(comment));
            return RedirectToAction("BlogDetails", "Blog", new { id = comment.BlogId });
        }
        [HttpPost]
        public IActionResult AddReplyComment(ReplyCommentViewModel replyComment)
        {
            replyComment.CommentDate = DateTime.Now;
            replyComment.CommentStatus = false;
            _commentReplyService.Add(_mapper.Map<CommentReply>(replyComment));
            return RedirectToAction("BlogDetails", "Blog", new { id = replyComment.BlogId });
        }
    }
}

WebApplication_Blog/ViewComponents/Comment/CommentViewComponent.cs
using AutoMapper;
using BuisnessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;
using WebApplication_Blog.ViewModels;

namespace WebApplication_Blog.ViewComponents.Comment
{
    public class CommentViewComponent : ViewComponent
    {
        private readonly ICommentService _commentService;
        private readonly IMapper _mapper;

        public CommentViewComponent(ICommentService commentService, IMapper mapper)
        {
            _commentService = commentService;
            _mapper = mapper;
        }
        public IViewComponentResult Invoke(int id) 
        {
            var values = _commentService.GetList(id).Where(x => x.CommentStatus == true);
            values.Reverse();
            return View(_mapper.Map<List<CommentViewModel>>(values)); 
        }
    }
}

WebApplication_Blog/ViewComponents/Reply/ReplyViewComponent.cs
using BuisnessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication_Blog.ViewComponents.Reply
{
    public class ReplyViewComponent : ViewComponent
    {
        private readonly ICommentReplyService _commentReplyService;

        public ReplyViewComponent(ICommentReplyService commentReplyService)
        {
            _commentReplyService = commentReplyService;
        }
        public IViewComponentResult Invoke(int id)
        {
            var value = _commentReplyService.GetReplyList(id).Where(x=>x.CommentStatus == true).ToList();
            return View(value);
        }
    }
}

WebApplication_Blog/Views/Shared/Components/Comment/Default.cshtml
@model List<CommentViewModel>

@if (Model.Count() == 0)
{
    <h4>Henüz Yorum Yok! İlk Yorumu Sen Yap.</h4>
}
else
{

    <div class="sidebar-item comments">
        <div class="sidebar-heading">
            <h2>@Model.Count() Adet Yorum</h2>
        </div>
        <div class="content">
            <ul>
                @foreach (var item in Model)
                {
                    <li style="display:block">
                        <div class="author-thumb">
                            <img class="rounded-circle w-75" src="~/images/commentimage.png" alt="">
                        </div>
                        <div class="right-content">
                            <h4>@item.CommentUserName<span>@item.CommentDate.ToString("dd-MMM-yyyy")</span></h4>
                            <p>@item.CommentContent</p>
                            <button class="btn btn-sm"  onclick="myFunction(@item.CommentId)">Yanıtla</button>
                        </div>
                        <div style="display:none" id="@item.CommentId">
                            @await Html.PartialAsync("AddReplyCommentPartial", new ReplyCommentViewModel{CommentId = item.CommentId,BlogId = item.BlogId})
                            
                        </div>
                    </li>
                    @await Component.InvokeAsync("Reply",item.CommentId)
                }

            </ul>
        </div>
    </div>

}

<script>
    function myFunction(id) {
        var x = document.getElementById(id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>